data_file <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?")
data_date <- subset(data_file, Date %in% c("1/2/2007","2/2/2007"))
data_date$Date <- as.Date(data_date$Date, format="%d/%m/%Y")
date_time <- paste(as.Date(data_date$Date), data_date$Time)
data_date$Datetime <- as.POSIXct(date_time)
with(data_date, {
  plot(Sub_metering_1~Datetime, type="l", ylab="Energy sub metering", xlab="")
  lines(Sub_metering_2~Datetime,col='Red')
  lines(Sub_metering_3~Datetime,col='Blue')
})
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png", height=480, width=480)
dev.off()
